from ursina_.shaders.unlit_shader import unlit_shader
from ursina_.shaders.lit_with_shadows_shader import lit_with_shadows_shader
from ursina_.shaders.normals_shader import normals_shader
from ursina_.shaders.basic_lighting_shader import basic_lighting_shader
from ursina_.shaders.triplanar_shader import triplanar_shader
from ursina_.shaders.matcap_shader import matcap_shader
from ursina_.shaders.colored_lights_shader import colored_lights_shader



# post processing effects
from ursina_.shaders.screenspace_shaders.camera_vertical_blur import camera_vertical_blur_shader
from ursina_.shaders.screenspace_shaders.camera_contrast import camera_contrast_shader
from ursina_.shaders.screenspace_shaders.camera_grayscale import camera_grayscale_shader
from ursina_.shaders.screenspace_shaders.fxaa import fxaa_shader
from ursina_.shaders.screenspace_shaders.ssao import ssao_shader
